# Generated by Django 5.0.4 on 2024-05-15 13:48

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='about',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=30)),
                ('last_name', models.CharField(max_length=30)),
                ('subject', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='iceCream',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('flavour', models.CharField(max_length=30)),
                ('size', models.CharField(max_length=30)),
                ('price', models.CharField(max_length=30)),
                ('offer_price', models.CharField(max_length=30)),
                ('icecream_photo', models.ImageField(max_length=200, upload_to='')),
                ('description', models.TextField()),
            ],
        ),
    ]
