# Generated by Django 3.2.12 on 2024-05-25 07:25

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='about',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('designation', models.CharField(max_length=30)),
                ('image', models.ImageField(default='', upload_to='static/about')),
                ('description', models.TextField()),
                ('email', models.EmailField(blank=True, max_length=70, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='carousel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('image', models.ImageField(default='', upload_to='static/carousel')),
                ('description', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fname', models.CharField(max_length=30)),
                ('lname', models.CharField(max_length=30)),
                ('country', models.CharField(max_length=30)),
                ('subject', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='iceCream',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('flavour', models.CharField(max_length=30)),
                ('size', models.CharField(max_length=30)),
                ('price', models.CharField(max_length=30)),
                ('offer_price', models.CharField(max_length=30)),
                ('icecream_photo', models.ImageField(default='', upload_to='static/icecream')),
                ('description', models.TextField()),
            ],
        ),
    ]
